import AbilityConstant from '@ohos.app.ability.AbilityConstant'
import hilog from '@ohos.hilog'
import UIAbility from '@ohos.app.ability.UIAbility'
import Want from '@ohos.app.ability.Want'
import window from '@ohos.window'

export default class EntryAbility extends UIAbility {
  onCreate(want: Want, launchParam: AbilityConstant.LaunchParam): void {
    hilog.info(0x0000, 'Xiangqi', 'onCreate')
  }

  onDestroy(): void {
    hilog.info(0x0000, 'Xiangqi', 'onDestroy')
  }

  onWindowStageCreate(windowStage: window.WindowStage): void {
    windowStage.loadContent('pages/Index', (err) => {
      if (err.code) {
        hilog.error(0x0000, 'Xiangqi', `Failed to load content: ${err.code}`)
      }
    })
  }

  onWindowStageDestroy(): void {
    hilog.info(0x0000, 'Xiangqi', 'onWindowStageDestroy')
  }

  onForeground(): void {
    hilog.info(0x0000, 'Xiangqi', 'onForeground')
  }

  onBackground(): void {
    hilog.info(0x0000, 'Xiangqi', 'onBackground')
  }
}
